#!/bin/bash

# ----------------------------------------------------------------------
# | Navigation                                                         |
# ----------------------------------------------------------------------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# ----------------------------------------------------------------------
# | Network                                                            |
# ----------------------------------------------------------------------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ "$OS" == "osx" ]; then
    alias local-ip="ipconfig getifaddr en1"
elif [ "$OS" == "ubuntu" ]; then
    alias local-ip="ifconfig | \
                   grep 'inet addr' | \
                   grep -v '127.0.0.1' | \
                   cut -d: -f2 | \
                   cut -d' ' -f1"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Copy to clipboard

if [ "$OS" == "osx" ]; then
    alias cc="pbcopy"
elif [ "$OS" == "ubuntu" ]; then
    alias cc="xclip -selection clip"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open

if [ "$OS" == "osx" ]; then
    alias o="open"
elif [ "$OS" == "ubuntu" ]; then
    alias o="xdg-open"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Custom

alias web='cd /home/andrew/Sites'
alias xamp='cd /opt/lampp'
alias dotfiles='cd ~/dotfiles'
alias devhost='xdg-open /opt/lampp/etc/extra/httpd-vhosts.conf; xdg-open /etc/hosts;'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -pv'
alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias upd='sudo apt-get update'
alias updall='sudo apt-get update; sudo apt-get upgrade; gem update;'
alias upg='sudo apt-get upgrade'
alias dupg='sudo apt-get dist-upgrade'
alias remv='sudo apt-get autoremove'
alias inst='sudo apt-get install'
alias sag='sudo apt-get'

alias newalias='xdg-open ~/.bash_aliases'

alias c='clear'
alias e='exit'

alias astart='sudo /opt/lampp/lampp start'
alias astop='sudo /opt/lampp/lampp stop'
alias are='sudo /opt/lampp/lampp restart'

alias gst='git status'
alias ga='git add'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gl='git pull'
alias gp='git push'
alias gpa='git push; git ftp push -v'
alias gre='git reset'
alias gcl='git clean'
alias gb='git branch'
alias gch='git checkout'
alias gdi='git diff'
alias gamend='git commit --amend'

alias drush='sudo drush'
alias s='subl .'
